### ISSUE TITLE
Repo & blogs post address problem different than described.

### ISSUE THREAD

**Issue by wzieba** [rubensousa/RecyclerViewNestedExample#3]
Hi @rubensousa!

Thanks for sharing your thoughts on your blogpost and repo. I've got though some comments on this and wanted to share them with you and every other dev spending time on RecyclerViews states.

I believe the problem your solution resolves is not the problem described by you [in your blogpost](https://rubensousa.com/2019/08/27/saving_scroll_state_of_nested_recyclerviews/). You wrote

> By default, if you scroll the parent RecyclerView, the nested RecyclerViews don’t save and restore state automatically.

but I believe it does. See my code change: https://github.com/rubensousa/RecyclerViewNestedExample/pull/2 . On this change (which disables `scrollStateHolder`) I've run your sample app with following result:

![Kapture 2020-03-20 at 19 47 12](https://user-images.githubusercontent.com/5845095/77196698-27244e80-6ae4-11ea-97d5-5d9f0ff290a8.gif)

which proves that indeed, the position has been saved without `scrollStateHolder` and after recycling item 0.

The issue you've resolved is that when using `scrollStateHolder` state is kept even after process kill (e.g. when using `Don't keep activities`) which is of course great.

The issue that is, I believe, resolved accidentally is that `scrollStateHolder` ensures by tags (`ScrollStateKey`) correct state of items. Your implementation in sample app has problem with indexing elements in recyclerview. And this is why you were able to record first gif [in your blogpost](https://rubensousa.com/2019/08/27/saving_scroll_state_of_nested_recyclerviews/).  
Images says more than words, below I've set position only on lists 0, 1 and 2. After scrolling you can see e.g. lists 14, 15 and 16 have moved.

![Kapture 2020-03-20 at 19 55 16](https://user-images.githubusercontent.com/5845095/77197139-ee38a980-6ae4-11ea-926e-c29d444fa99d.gif)

I would love to hear your thoughts about it. If you agree with those comments I would encourage you to maybe update your blogpost and repo as they are quite popular and those changes might be helpful for devs.

**Comment by rubensousa** [comment]
Hi @wzieba 
Thanks for checking out this sample.

> but I believe it does. See my code change: #2 . On this change (which disables scrollStateHolder) I've run your sample app with following result:

If you try scrolling further, the item in position 0 will have an incorrect state. You're showing that the ViewHolder was recycled, but it wasn't probably rebound to another list yet. If you scroll further, the ViewHolder that was used in position 0 will be used by another position (e.g position 10) and then the scroll state will be lost forever.

``scrollStateHolder`` makes sure each position has it's own scroll state restored. It's required if you have different lists for every position.

You can think of the problem in this way: We only have 10 ViewHolders, but the data set might have size N = 1000. RecyclerView will just hold the state of 10 items (because it has 10 ViewHolders), but we want to save the state of all N items.

Let me know if there's anything else you might find incorrect.

**Comment by wzieba** [comment]
Hi again @rubensousa 👋 

> but it wasn't probably rebound to another list yet

Yes, this is the crucial part I've missed! Thanks a lot for clarification, indeed position is completely lost and `scrollStateHolder` indeed works well with saving its state. Sorry for trouble, thanks again for reply and whole blog/repository, helped me a lot :).

**Comment by rubensousa** [comment]
No problem! I'm glad I could help
